import fs from 'node:fs'
import path from 'node:path'
for (const folder of ['client/src', 'server/src', 'e2e']) {
  for (const name of fs.readdirSync(folder,{recursive:true})) {
    if (!/\.tsx?$/.test(name)) continue
    const file=path.join(folder,name)
    let s=fs.readFileSync(file,'utf8').replaceAll('mohcc_admin','public_health_analyst')
    if (folder==='server/src' && path.dirname(name)==='routes') s=s.replace('import { Router } from "express"','import { Router } from "../lib/router.js"')
    fs.writeFileSync(file,s)
  }
}
for (const [file, scripts] of [['server/package.json',{migrate:'tsx scripts/migrate.ts',test:'tsx --test tests/*.test.ts'}],['package.json',{migrate:'pnpm --filter server migrate'}]]) {
  const json=JSON.parse(fs.readFileSync(file,'utf8')); Object.assign(json.scripts,scripts); fs.writeFileSync(file,JSON.stringify(json,null,2)+'\n')
}
function edit(file, fn) { fs.writeFileSync(file,fn(fs.readFileSync(file,'utf8'))) }
edit('server/src/auth/middleware.ts',s=>s.replace('import { query }','import { consumeCode } from "./totp.js"\nimport { query }').replace('req.method === "GET" && typeof req.query.token','req.method === "GET" && /^\\/api\\/(images\\/[^/]+\\/file|notifications\\/[^/]+\\/certificate)$/.test(req.originalUrl.split("?")[0]) && typeof req.query.token').replace('rows[0]?.enabled === true','Boolean(rows[0]?.enabled)').replace('// Verify TOTP code (implementation would use speakeasy or similar)\n    // For now, skip verification','if (!await consumeCode(req.user.userId, tfaCode)) return res.status(403).json({ error: "Invalid or already used 2FA code" })'))
edit('server/src/auth/middleware.ts',s=>s.replace('const rateLimitMap = new Map<string, { count: number; resetTime: number }>()','').replace('return (req: Request, res: Response, next: NextFunction) => {\n    const key = req.ip', 'const rateLimitMap = new Map<string, { count: number; resetTime: number }>()\n  return (req: Request, res: Response, next: NextFunction) => {\n    if (rateLimitMap.size > 10000) for (const [key, value] of rateLimitMap) if (value.resetTime < Date.now()) rateLimitMap.delete(key)\n    const key = req.ip'))
edit('server/src/routes/auth.ts',s=>s.replace('import { requireAuth }','import { consumeCode } from "../auth/totp.js"\nimport { requireAuth, rateLimiter }').replace('password: z.string().min(1),','password: z.string().min(1).max(256),\n  code: z.string().max(32).optional(),').replace('authRouter.post("/login", async','authRouter.post("/login", rateLimiter(30), async').replace('FROM users WHERE email = ?', 'FROM users WHERE email = ? OR user_id IN (SELECT user_id FROM email_aliases WHERE email = ? AND expires_at > NOW())').replace('[email.toLowerCase()],','[email.toLowerCase(), email.toLowerCase()],').replace('const newAttempts = (user.failed_login_attempts || 0) + 1','const newAttempts = (user.locked_until && new Date(user.locked_until) <= new Date() ? 0 : (user.failed_login_attempts || 0)) + 1').replace('// Reset failed login attempts on successful login',`const [tfa] = await query<any[]>("SELECT enabled FROM two_factor_auth WHERE user_id = ?", [user.user_id])
  if (tfa?.enabled) {
    if (!parsed.data.code) return res.status(403).json({ error: "Enter your authenticator or recovery code", requiresTwoFactor: true })
    if (!await consumeCode(user.user_id, parsed.data.code)) {
      await query("UPDATE users SET failed_login_attempts=failed_login_attempts+1, locked_until=IF(failed_login_attempts>=5, DATE_ADD(NOW(), INTERVAL 15 MINUTE), NULL) WHERE user_id=?", [user.user_id])
      await writeAudit(req, { userId: user.user_id, action: "login_failed_2fa", entityType: "auth" })
      return res.status(403).json({ error: "Invalid or already used verification code" })
    }
  }
  // Reset failed login attempts on successful login`))
edit('server/src/routes/user-profile.ts',s=>s.replace('import { query }', 'import crypto from "node:crypto"\nimport { query }').replace('userProfileRouter.get("/",','userProfileRouter.get(["/", "/profile"],').replace('userProfileRouter.patch("/",','userProfileRouter.patch(["/", "/profile"],').replace('z.string().min(2).optional()', 'z.string().trim().min(2).max(255).optional()').replace('phone: z.string().optional()', 'phone: z.string().max(50).optional()').replace('department: z.string().optional()', 'department: z.string().max(100).optional()').replace('language: z.string().optional()', 'language: z.enum(["en", "sn", "nd"]).optional()').replace('timezone: z.string().optional()', 'timezone: z.string().max(50).refine(v => { try { new Intl.DateTimeFormat("en", { timeZone: v }); return true } catch { return false } }).optional()').replace('res.json({ items: sessions })', 'res.json({ items: sessions.map(s => ({ ...s, current: s.session_id === req.user!.sessionId })) })').replace('JSON.parse(pref.preference_value)', 'typeof pref.preference_value === "string" ? JSON.parse(pref.preference_value) : pref.preference_value').replace('if (!key || value === undefined)', 'if (!(["theme", "language"].includes(key)) || (key === "theme" && !["light", "dark", "system"].includes(value)) || (key === "language" && !["en", "sn", "nd"].includes(value)))'))
edit('server/src/routes/notifications.ts',s=>s.replace('import crypto', 'import { canAccessNotification, facilityScoped } from "../lib/access.js"\nimport crypto').replace('export const notificationsRouter = Router()', 'export const notificationsRouter = Router()\nnotificationsRouter.use(requireAuth, requireRole("medical_officer", "mortuary_clerk", "pathologist", "public_health_analyst", "system_admin"))').replaceAll('req.user!.role === "medical_officer"','facilityScoped(req.user!)').replace('requireRole("medical_officer", "public_health_analyst", "system_admin")', 'requireRole("medical_officer", "mortuary_clerk", "public_health_analyst", "system_admin")').replace('where.push("dn.reported_by = ?")\n      params.push(req.user!.userId)', 'where.push("1 = 0")').replace('res.json({ items: rows })', 'res.json({ items: rows.map(row => req.user!.role === "mortuary_clerk" ? { ...row, clinical_summary: null } : row) })').replace('const d = parsed.data\n\n    // Medical', 'const d = parsed.data\n    if (facilityScoped(req.user!) && !req.user!.facilityId) return res.status(403).json({ error: "No facility assigned" })\n\n    // Medical').replace('  const rows = await query<any[]>(`${LIST_SELECT} WHERE dn.notification_id = ?`', '  if (!await canAccessNotification(req.user!, req.params.id)) return res.status(403).json({ error: "Record unavailable" })\n  const rows = await query<any[]>(`${LIST_SELECT} WHERE dn.notification_id = ?`').replace('  const images = await query<any[]>(', '  if (req.user!.role === "mortuary_clerk") return res.json({ notification: { ...row, clinical_summary: null }, images: [], autopsy: null })\n  const images = await query<any[]>(').replace('const d = parsed.data\n    if (!d.status', 'const d = parsed.data\n    if (!await canAccessNotification(req.user!, req.params.id) || req.user!.role === "mortuary_clerk") return res.status(403).json({ error: "Forbidden" })\n    if (!d.status'))
edit('server/src/routes/autopsies.ts',s=>s.replace('export const autopsiesRouter = Router()', 'export const autopsiesRouter = Router()\nautopsiesRouter.use(requireAuth, requireRole("pathologist", "public_health_analyst", "system_admin"))'))
edit('server/src/routes/images.ts',s=>s.replace('import multer', 'import { canAccessNotification } from "../lib/access.js"\nimport multer').replace('    if (!req.file)', '    if (!await canAccessNotification(req.user!, req.params.id, true)) return res.status(403).json({ error: "Forbidden" })\n    if (!req.file)').replace('  const rows = await query<any[]>(\n    `SELECT i.image_id', '  if (!await canAccessNotification(req.user!, req.params.id, true)) return res.status(403).json({ error: "Forbidden" })\n  const rows = await query<any[]>(\n    `SELECT i.image_id').replace('SELECT file_path, mime_type FROM', 'SELECT file_path, mime_type, notification_id FROM').replace('  const abs =', '  if (!await canAccessNotification(req.user!, row.notification_id, true)) return res.status(403).json({ error: "Forbidden" })\n  const abs ='))
edit('server/src/routes/certificates.ts',s=>s.replace('import { Router }', 'import { canAccessNotification } from "../lib/access.js"\nimport { Router }').replace('  const rows =', '  if (!await canAccessNotification(req.user!, req.params.id)) return res.status(403).json({ error: "Forbidden" })\n  const rows ='))
edit('server/src/routes/patients.ts',s=>s.replace('import { requireAuth }', 'import { requireAuth, requireRole }').replace('requireAuth, async', 'requireAuth, requireRole("public_health_analyst", "pathologist", "system_admin"), async'))
edit('server/src/routes/alerts.ts',s=>s.replace('res.json({ items: rows })','res.json({ items: rows.map(row => req.user!.role === "executive" ? { ...row, cluster_data: null } : row) })'))
edit('server/src/routes/analytics.ts',s=>s.replace('analyticsRouter.get("/trends", requireAuth, requireRole(...ANALYST_ROLES)', 'analyticsRouter.get("/trends", requireAuth, requireRole(...ANALYST_ROLES, "executive")'))
