import { useEffect,useState } from "react"
import useSWR from "swr"
import { toast } from "sonner"
import { api } from "@/lib/api"
import { usePreferences, LANGUAGES, LANGUAGE_CODES } from "@/lib/preferences"
import { Workspace,Panel,Field,Action,LoadState } from "@/components/workspace"

export default function UserProfile(){const{t}=usePreferences();
  const {data,error,mutate}=useSWR<any>("/user/profile",api),sessions=useSWR<any>("/user/sessions",api),factor=useSWR<any>("/user/two-factor",api)
  const [name,setName]=useState(""),[phone,setPhone]=useState(""),[department,setDepartment]=useState(""),[current,setCurrent]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[secret,setSecret]=useState(""),[codes,setCodes]=useState<string[]>([])
  const prefs=usePreferences()
  useEffect(()=>{if(data){setName(data.user.full_name);setPhone(data.user.phone||"");setDepartment(data.user.department||"")}},[data])
  const strong=password.length>=8&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/\d/.test(password)
  const send=(path:string,body:unknown)=>api(path,{method:"POST",body:JSON.stringify(body)})
  return <Workspace title={t("My Profile")} description={t("Manage your contact details, preferences and account security.")}><LoadState error={error}/><div className="grid gap-6 lg:grid-cols-2"><Panel title={t("Personal details")}><p className="text-sm text-muted-foreground">{data?.user.email}</p><Field label={t("Full name")} value={name} onChange={setName}/><Field label="Phone" value={phone} onChange={setPhone}/><Field label="Department" value={department} onChange={setDepartment}/><Action onClick={async()=>{await api("/user/profile",{method:"PATCH",body:JSON.stringify({fullName:name,phone,department})});await mutate();toast.success(t("Profile saved"))}}>{t("Save profile")}</Action></Panel>
  <Panel title={t("Appearance and language")}><label className="block text-sm">Theme<select className="mt-2 block w-full rounded-md border bg-background p-2" value={prefs.theme} onChange={e=>prefs.setTheme(e.target.value as any)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option><option value="hc">{t("High contrast (specs friendly)")}</option></select></label><label className="block text-sm">Language<select className="mt-2 block w-full rounded-md border bg-background p-2" value={prefs.language} onChange={e=>prefs.setLanguage(e.target.value as any)}>{LANGUAGE_CODES.map(c=><option key={c} value={c}>{LANGUAGES[c].nativeName}{LANGUAGES[c].draft?" (draft)":""}</option>)}</select></label><p className="text-xs text-muted-foreground">{prefs.languageInfo.note??"Navigation translations are available. Clinical terminology remains in English pending language review."}</p></Panel>
  <Panel title={t("Change password")}><Field label={t("Current password")} type="password" value={current} onChange={setCurrent}/><Field label={t("New password")} type="password" value={password} onChange={setPassword}/><p className="text-xs" role="status">{strong?"Password meets requirements":"Use at least 8 characters, uppercase, lowercase and a number."}</p><Action onClick={async()=>{if(!strong)throw Error(t("Password does not meet requirements"));await send("/user/change-password",{currentPassword:current,newPassword:password});setCurrent("");setPassword("");sessions.mutate();toast.success(t("Password changed; other sessions revoked"))}}>{t("Change password")}</Action></Panel>
  <Panel title={t("Two-factor authentication")}><LoadState error={factor.error}/><p className="text-sm">Status: {factor.data?.enabled?"Enabled":"Not enabled"}</p><Field label={t("Password to confirm security changes")} type="password" value={current} onChange={setCurrent}/>{!factor.data?.enabled&&!secret&&<Action onClick={async()=>{const r=await send("/user/enable-2fa",{password:current});setSecret(r.secret)}}>{t("Set up authenticator")}</Action>}{secret&&<div className="space-y-2 text-sm"><p>{t("Add this setup key to your authenticator as a time-based DDS account.")}</p><code className="block break-all rounded bg-muted p-3 select-all">{secret}</code></div>}{(secret||factor.data?.enabled)&&<><Field label={t("Authenticator or recovery code")} value={code} onChange={setCode}/><Action onClick={async()=>{if(factor.data?.enabled){await send("/user/disable-2fa",{password:current,code});toast.success(t("Two-factor authentication disabled"))}else{const r=await send("/user/verify-2fa",{code});setCodes(r.backupCodes);setSecret("");toast.success(t("Two-factor authentication enabled"))}setCode("");factor.mutate();sessions.mutate()}}>{factor.data?.enabled?"Disable two-factor authentication":"Verify and enable"}</Action></>}{codes.length>0&&<div><p className="text-sm font-medium">{t("Save these recovery codes now. Each works once.")}</p><pre className="mt-2 rounded bg-muted p-3 text-sm select-all">{codes.join("\n")}</pre></div>}</Panel></div>
  <Panel title={t("Active sessions")}><LoadState error={sessions.error}/><Action variant="outline" onClick={async()=>{await api("/user/sessions",{method:"DELETE"});sessions.mutate();toast.success(t("Other sessions revoked"))}}>{t("Sign out other devices")}</Action><div className="divide-y">{sessions.data?.items.filter((s:any)=>!s.revoked&&new Date(s.expires_at)>new Date()).map((s:any)=><div className="flex flex-wrap items-center justify-between gap-3 py-3" key={s.session_id}><div className="min-w-0 text-sm"><p className="max-w-xl truncate">{s.user_agent||"Unknown device"}</p><p className="text-xs text-muted-foreground">{s.ip_address} • {new Date(s.created_at).toLocaleString()} {s.current?"• This device":""}</p></div>{!s.current&&<Action variant="outline" onClick={async()=>{await api(`/user/sessions/${s.session_id}`,{method:"DELETE"});sessions.mutate()}}>Revoke</Action>}</div>)}</div></Panel></Workspace>
}
