import { useState } from "react"
import useSWR from "swr"
import { toast } from "sonner"
import { api } from "@/lib/api"
import { Workspace,Panel,Field,Action,LoadState,Rows } from "@/components/workspace"
import { usePreferences } from "@/lib/preferences"
const post=(url:string,body:unknown)=>api(url,{method:"POST",body:JSON.stringify(body)})

export function MpdsrPage(){const{t}=usePreferences();
  const {data,error,isLoading,mutate}=useSWR<any>("/mpdsr/workflows",api),[id,setId]=useState(""),[department,setDepartment]=useState("Maternal and Perinatal Review Team")
  return <Workspace title={t("MPDSR Workflows")} description={t("Reviews start automatically for flagged notifications. Department names identify the review team; external email and SMS dispatch are not configured.")}><Panel title={t("Initiate a review")}><div className="grid gap-4 md:grid-cols-2"><Field label={t("Notification ID")} value={id} onChange={setId}/><Field label={t("Review department")} value={department} onChange={setDepartment}/></div><Action onClick={async()=>{await post("/mpdsr/initiate",{notificationId:id,department});mutate();toast.success(t("Review initiated"))}}>{t("Initiate review")}</Action></Panel><LoadState error={error} loading={isLoading} empty={data?.items.length===0}/>{data?.items.map((w:any)=><Workflow key={w.workflow_id} item={w} refresh={mutate}/>)}</Workspace>
}
function Workflow({item,refresh}:{item:any;refresh:()=>unknown}){const{t}=usePreferences();const [notes,setNotes]=useState(item.investigation_notes||""),[status,setStatus]=useState(item.response_status);return <Panel title={item.facility_name}><p className="text-xs text-muted-foreground">{item.notification_id} • {item.department_notified}</p><label className="block text-sm">{t("Review status")}<select className="ml-3 rounded border bg-background p-2" value={status} onChange={e=>setStatus(e.target.value)}>{["pending","investigating","completed"].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">{t("Investigation notes")}<textarea className="mt-2 block w-full rounded border bg-background p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label><Action onClick={async()=>{await api(`/mpdsr/workflows/${item.workflow_id}`,{method:"PATCH",body:JSON.stringify({status,notes})});refresh();toast.success(t("Review updated"))}}>{t("Save review")}</Action></Panel>}
export function ThresholdPage(){const{t}=usePreferences();
  const {data,error,mutate}=useSWR<any>("/alerts/thresholds",api),[district,setDistrict]=useState(""),[category,setCategory]=useState(""),[count,setCount]=useState("8"),[hours,setHours]=useState("48")
  return <Workspace title={t("Alert Thresholds")} description={t("Configure district and disease reporting thresholds. Leave a filter blank to match all values.")}><Panel title={t("New detection rule")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("District (optional)")} value={district} onChange={setDistrict}/><Field label={t("Disease category (optional)")} value={category} onChange={setCategory}/><Field label={t("Minimum reported deaths")} value={count} onChange={setCount} type="number"/><Field label={t("Time window (hours)")} value={hours} onChange={setHours} type="number"/></div><p className="text-sm text-muted-foreground">Trigger at {count} reported deaths within {hours} hours.</p><Action onClick={async()=>{await post("/alerts/thresholds",{district:district||null,diseaseCategory:category||null,caseThreshold:Number(count),timeWindowHours:Number(hours)});mutate();toast.success(t("Threshold saved"))}}>{t("Save rule")}</Action></Panel><LoadState error={error} empty={data?.items.length===0}/>{data?.items.map((r:any)=><Panel key={r.threshold_id} title={`${r.district||"All districts"} • ${r.disease_category||"All categories"}`}><p className="text-sm">{r.case_threshold} deaths / {r.time_window_hours} hours • {r.is_active?"Active":"Inactive"}</p><div className="flex gap-3"><Action variant="outline" onClick={async()=>{await api(`/alerts/thresholds/${r.threshold_id}`,{method:"PATCH",body:JSON.stringify({district:r.district,diseaseCategory:r.disease_category,caseThreshold:r.case_threshold,timeWindowHours:r.time_window_hours,priority:r.alert_priority,active:!r.is_active})});mutate()}}>{r.is_active?"Deactivate":"Activate"}</Action><Action variant="outline" onClick={async()=>{await api(`/alerts/thresholds/${r.threshold_id}`,{method:"DELETE"});mutate()}}>{t("Delete rule")}</Action></div></Panel>)}</Workspace>
}
export function CrossBorderPage(){const{t}=usePreferences();
  const {data,error,mutate}=useSWR<any>("/cross-border/cases",api),[id,setId]=useState(""),[country,setCountry]=useState(""),[crossing,setCrossing]=useState(""),[history,setHistory]=useState("")
  return <Workspace title={t("Cross-border Tracking")} description={t("Record reported travel history for surveillance review.")}><Panel title={t("Mark a case")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("Notification ID")} value={id} onChange={setId}/><Field label={t("Source country")} value={country} onChange={setCountry}/><Field label={t("Border crossing")} value={crossing} onChange={setCrossing}/><Field label={t("Travel history")} value={history} onChange={setHistory}/></div><Action onClick={async()=>{await post("/cross-border/mark",{notificationId:id,sourceCountry:country,borderCrossingPoint:crossing,travelHistory:history});mutate();toast.success(t("Travel history recorded"))}}>{t("Save case")}</Action></Panel><LoadState error={error} empty={data?.items.length===0}/>{data?.items.length>0&&<Rows items={data.items} columns={[["source_country","Source country"],["border_crossing_point","Crossing"],["district","District"],["travel_history","Travel history"]]}/>}</Workspace>
}
