import { canAccessNotification } from "../lib/access.js"
import { Router } from "../lib/router.js"
import { requireAuth } from "../auth/middleware.js"
import { query } from "../db.js"

export const certificatesRouter = Router()

function esc(s: unknown) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!))
}

// Printable digital death certificate (Ch 4.3 output). Served as styled HTML —
// the browser's print dialog produces the PDF/legal printout.
certificatesRouter.get("/notifications/:id/certificate", requireAuth, async (req, res) => {
  if (!await canAccessNotification(req.user!, req.params.id)) return res.status(403).json({ error: "Forbidden" })
  const rows = await query<any[]>(
    `SELECT dn.notification_id, dn.date_of_death, dn.preliminary_icd_code,
            p.full_name AS patient_name, p.national_id, p.age, p.gender, p.residential_address,
            f.facility_name, f.district, f.province,
            a.final_icd_code, a.final_cause_of_death, a.digital_signature, a.finalized_at,
            u.full_name AS pathologist_name
     FROM death_notifications dn
     JOIN patients p ON p.patient_id = dn.patient_id
     JOIN facilities f ON f.facility_id = dn.facility_id
     LEFT JOIN autopsy_reports a ON a.notification_id = dn.notification_id AND a.status = 'finalized'
     LEFT JOIN users u ON u.user_id = a.pathologist_id
     WHERE dn.notification_id = ?`,
    [req.params.id],
  )
  const r = rows[0]
  if (!r) return res.status(404).json({ error: "Notification not found" })
  if (!r.final_icd_code) return res.status(409).json({ error: "Certificate available only after autopsy finalization" })

  res.type("html").send(`<!doctype html>
<html><head><meta charset="utf-8"><title>Death Certificate ${esc(r.notification_id)}</title>
<style>
  body{font-family:Georgia,serif;max-width:720px;margin:40px auto;padding:32px;border:2px solid #1c2733}
  h1{font-size:20px;text-align:center;letter-spacing:1px} h2{font-size:13px;text-align:center;font-weight:normal;color:#555;margin-top:-8px}
  table{width:100%;border-collapse:collapse;margin-top:24px;font-size:14px}
  td{padding:8px 10px;border-bottom:1px solid #ddd;vertical-align:top}
  td:first-child{width:42%;color:#555;font-size:12px;text-transform:uppercase;letter-spacing:.5px}
  .sig{margin-top:48px;display:flex;justify-content:space-between;font-size:13px}
  .sig div{border-top:1px solid #333;padding-top:6px;width:45%}
  .meta{margin-top:24px;font-size:11px;color:#777;text-align:center}
  @media print{body{border:none;margin:0}}
</style></head><body>
<h1>MINISTRY OF HEALTH AND CHILD CARE — ZIMBABWE</h1>
<h2>Disease Detection System · Digital Death Certificate</h2>
<table>
  <tr><td>Deceased full name</td><td>${esc(r.patient_name)}</td></tr>
  <tr><td>National ID</td><td>${esc(r.national_id ?? "—")}</td></tr>
  <tr><td>Age / Gender</td><td>${esc(r.age ?? "—")} / ${esc(r.gender)}</td></tr>
  <tr><td>Residential address</td><td>${esc(r.residential_address ?? "—")}</td></tr>
  <tr><td>Date of death</td><td>${esc(new Date(r.date_of_death).toLocaleString("en-GB"))}</td></tr>
  <tr><td>Certified cause of death</td><td>${esc(r.final_cause_of_death)} (${esc(r.final_icd_code)})</td></tr>
  <tr><td>Reporting facility</td><td>${esc(r.facility_name)}, ${esc(r.district)}, ${esc(r.province)}</td></tr>
  <tr><td>Pathologist</td><td>${esc(r.pathologist_name)}</td></tr>
  <tr><td>Finalized</td><td>${esc(r.finalized_at ? new Date(r.finalized_at).toLocaleString("en-GB") : "—")}</td></tr>
</table>
<div class="sig">
  <div>Digital signature:<br><strong>${esc(r.digital_signature)}</strong></div>
  <div>Certificate ref:<br><strong>${esc(r.notification_id)}</strong></div>
</div>
<p class="meta">Generated by DDS — verify authenticity against the system audit trail.</p>
</body></html>`)
})
