ALTER TABLE two_factor_auth ADD COLUMN last_counter BIGINT NOT NULL DEFAULT -1;
ALTER TABLE audit_log ADD COLUMN chain_sequence BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE;
CREATE TABLE IF NOT EXISTS email_aliases (
  email VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  expires_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notification_submissions (
  submission_id VARCHAR(100) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  notification_id VARCHAR(36),
  payload_hash VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
