// Validates the i18n dictionaries.
//   node scripts/check-i18n.mjs          — check mode (CI-safe, exit 1 on errors)
//   node scripts/check-i18n.mjs --scan   — scan t()/tr() call sites and
//                                          regenerate i18n/lang/en.json
//
// Keys are English literals:
//   web   : t('...')      in client/src/**.{ts,tsx}
//   mobile: tr('...')/context.tr('...') in mobile/lib/**.dart
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const langDir = join(root, "i18n", "lang")
const languages = JSON.parse(readFileSync(join(root, "i18n", "languages.json"), "utf8"))
const codes = Object.keys(languages)

function* walk(dir, exts) {
  if (!existsSync(dir)) return
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) yield* walk(p, exts)
    else if (exts.some(x => e.endsWith(x))) yield p
  }
}

const unescape = s => s.replace(/\\(['"\\])/g, "$1")

function scanKeys() {
  const keys = new Set()
  const add = m => { if (m) keys.add(unescape(m)) }
  // t('...') or t("...") — first arg only; skips t(var)
  const tsRe = /\bt\(\s*'((?:[^'\\]|\\.)*)'|\bt\(\s*"((?:[^"\\]|\\.)*)"/g
  // tr('...'), context.tr('...'), .tr('...')
  const dartRe = /\btr\(\s*'((?:[^'\\]|\\.)*)'|\btr\(\s*"((?:[^"\\]|\\.)*)"/g
  for (const f of walk(join(root, "client", "src"), [".ts", ".tsx"])) {
    const src = readFileSync(f, "utf8")
    for (const m of src.matchAll(tsRe)) add(m[1] ?? m[2])
  }
  for (const f of walk(join(root, "mobile", "lib"), [".dart"])) {
    const src = readFileSync(f, "utf8")
    for (const m of src.matchAll(dartRe)) add(m[1] ?? m[2])
  }
  return [...keys].sort((a, b) => a.localeCompare(b))
}

const placeholderRe = /\{[^{}]+\}/g
const metaKeys = new Set(["_meta"])
let errors = 0
const err = m => { errors++; console.error("  ✗ " + m) }
const warn = m => console.warn("  ! " + m)

if (process.argv.includes("--scan")) {
  const keys = scanKeys()
  const out = { _meta: "Generated by `pnpm i18n:scan` — keys are English source strings." }
  for (const k of keys) out[k] = k
  writeFileSync(join(langDir, "en.json"), JSON.stringify(out, null, 2) + "\n")
  console.log(`i18n:scan — wrote ${keys.length} keys to i18n/lang/en.json`)
  process.exit(0)
}

const en = JSON.parse(readFileSync(join(langDir, "en.json"), "utf8"))
const enKeys = Object.keys(en).filter(k => !metaKeys.has(k))
const referenced = new Set(scanKeys())

for (const code of codes) {
  const file = join(langDir, `${code}.json`)
  if (!existsSync(file)) { err(`${code}.json missing`); continue }
  let dict
  try { dict = JSON.parse(readFileSync(file, "utf8")) }
  catch (e) { err(`${code}.json invalid JSON: ${e.message}`); continue }
  const keys = new Set(Object.keys(dict).filter(k => !metaKeys.has(k)))
  if (code === "en" || code === "zsl") continue // en = inventory, zsl = meta-only by design
  let missing = 0
  for (const k of enKeys) {
    if (!keys.has(k)) missing++
    else {
      const need = k.match(placeholderRe) ?? []
      for (const p of need) if (!String(dict[k]).includes(p)) err(`${code}: "${k.slice(0, 50)}…" lost placeholder ${p}`)
    }
  }
  if (missing) warn(`${code}.json missing ${missing}/${enKeys.length} keys (English fallback applies)`)
  for (const k of keys) if (!enKeys.includes(k)) warn(`${code}.json stale key not in en.json: ${k.slice(0, 60)}`)
}

// Keys used in code but absent from every non-en dictionary are fine (fallback);
// keys in en.json never referenced in code are drift.
let orphan = 0
for (const k of enKeys) if (!referenced.has(k)) { orphan++; warn(`en.json key not referenced in code: ${k.slice(0, 70)}`) }

console.log(`i18n:check — ${codes.length} languages, ${enKeys.length} inventory keys, ${referenced.size} referenced${orphan ? `, ${orphan} unreferenced` : ""}`)
if (errors) { console.error(`FAILED with ${errors} error(s)`); process.exit(1) }
console.log("OK")
